name: golangci-lint Checks

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - .github/workflows/golangci-lint.yml
      - .ci/.golangci*.yml
      - .ci/tools/**
      - internal/**
      - go.sum
      - main.go
      - names/**
      - tools/**

jobs:
  golangci-linta:
    name: 1 of 2
    runs-on: [custom, linux, large]
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          cache: false
      - id: golangci-lint-version
        working-directory: .ci/tools
        run: >-
          echo "version=$(
            go list -m all |
            grep github.com/golangci/golangci-lint |
            awk '{print $2}'
          )" >> $GITHUB_OUTPUT
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v3.7.1
        with:
          version: "${{ steps.golangci-lint-version.outputs.version }}"
          args: --config .ci/.golangci.yml
  golangci-lintb:
    name: 2 of 2
    needs: [golangci-linta]
    runs-on: [custom, linux, xl]
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          cache: false
      - id: golangci-lint-version
        working-directory: .ci/tools
        run: >-
          echo "version=$(
            go list -m all |
            grep github.com/golangci/golangci-lint |
            awk '{print $2}'
          )" >> $GITHUB_OUTPUT
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v3.7.1
        with:
          version: "${{ steps.golangci-lint-version.outputs.version }}"
          args: --config .ci/.golangci2.yml
        env:
          # Trigger garbage collection more frequently to reduce the likelihood
          # of OOM errors.
          # ref: https://golangci-lint.run/usage/performance/#memory-usage
          GOGC: "50"
